```{r}
library(DECIPHER); library(ape); library(DESeq2); library(ggplot2); library(ggthemes); library(phyloseq); library(vegan)
library(philr); library(tidyverse); library(adespatial); library(devtools); library(qiime2R); library(MicrobeR); library(microbiome)
library(pander); library(grid); library(gridExtra); library(knitr); library(png); library(ggdendro); library(ggpubr)
library(RColorBrewer); library(microbiomeutilities); library(microbiomeSeq); library(viridis); library(DEFormats); library(corncob)
```

```{r}
calculate_abundance = function(p, gen, transpose = F, gr = F){
  d = MicrobeR::Summarize.Taxa(p@otu_table, as.data.frame(p@tax_table))[[gen]]
  nms = str_split(rownames(d), pattern = ";", simplify = T)
  for (i in 1:nrow(nms)){
    rownames(d)[i] = ifelse(nms[i, ncol(nms)] == "NA", "Unknown", nms[i, ncol(nms)])
  }
  if (transpose){
    d = data.frame(t(rbind(Sample = colnames(d), d)))
    if (gr == TRUE){
      d$Sample = p@sam_data$group
      d = pivot_longer(d, cols = 2:ncol(d), names_to = "group", values_to = "Abundance")
    } else{
      d = pivot_longer(d, cols = 2:ncol(d), names_to = gen, values_to = "Abundance")
    }
    d$Abundance = as.numeric(d$Abundance)
  }
  return(d)
}

```



```{r}
ASVs                <- read_qza("table.qza")
OTU                 <- otu_table(as.data.frame(ASVs$data), taxa_are_rows = T)
metadata            <- read.table("sample_metadata.tsv",header=T, row.names=1, comment="")
#colnames(metadata)  <- c("sample", "group")
metadata$group      <- toupper(metadata$group)
rownames(metadata)  <- toupper(rownames(metadata))
#metadata <- metadata[-1,] # remove the second line that specifies the data type
tree                <- read_qza("rooted-tree.qza")
taxonomy            <- read_qza("taxonomy.qza")
taxtable            <- base::do.call(rbind, strsplit(as.character(taxonomy$data$Taxon), ";")) %>% 
  as.matrix(, nrow(ASVs$data), length(.)/nrow(ASVs$data)) %>% as.data.frame()
colnames(taxtable)  <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")
rownames(taxtable)  <- taxonomy$data$Feature.ID
taxtable            <- taxtable[rownames(ASVs$data), ]
rownames(taxtable)  <- rownames(ASVs$data)
TAX                 <- tax_table(taxtable)
```


```{r}
#physeq <- phyloseq(OTU, TAX, sample_data(metadata))
physeq <- qza_to_phyloseq("table.qza", "rooted-tree.qza", "taxonomy.qza","sample_metadata.tsv")
colnames(physeq@otu_table) = toupper(colnames(physeq@otu_table))
rownames(physeq@sam_data) = toupper(rownames(physeq@sam_data))
physeq

plot_bar(physeq, fill = "Phylum")

plot_bar(physeq, fill = "group")

plot_bar(physeq, fill = "Phylum", facet_grid = ~Phylum)

physeq_filter = physeq
physeq_filter@sam_data = physeq_filter@sam_data[!(rownames(physeq_filter@sam_data) %in% c('S36')), ]
physeq_filter@otu_table = physeq_filter@otu_table[, !(colnames(physeq_filter@otu_table) %in% c('S36'))]

plot_bar(physeq_filter, fill = "Phylum")

physeq_norm <-normalise_data(physeq_filter, norm.method = "varstab")

plot_bar(physeq_norm, fill = "Phylum")
```

Top 20 najczęstszych OTU
```{r}
physeq_top20 <- sort(taxa_sums(physeq_norm), TRUE)[1:20]
physeq_top20 <- prune_taxa(names(physeq_top20), physeq_norm)

plot_bar(physeq_top20, fill = "Genus")

#Z jakiej rodziny należy ten top
tax_table(physeq_top20)[, "Family"] %>% as.vector()

plot_heatmap(physeq_top20, "PCoA", "bray", low="#000033", high="#CCFF66")

plot_tree(physeq_top20, ladderize = "left", color = "group", shape = "group")
```

```{r}
data.frame(values = colSums(OTU@.Data), sample = names(colSums(OTU@.Data))) %>% 
  ggplot(., aes(x = sample, y = values)) + geom_bar(stat = "identity") + theme_classic()

data.frame(values = colSums(OTU@.Data), sample = names(colSums(OTU@.Data))) %>% 
  ggplot(., aes(x = values)) + geom_histogram(bins = 12, col = "white") + theme_classic() + 
  labs(x = "Abundance", y = "Number of samples") + ylim(0, 11)
```


```{r}
table(phyloseq::tax_table(physeq_norm)[, "Phylum"])
ps_rel_abund = phyloseq::transform_sample_counts(physeq, function(x){x / sum(x)})

phyloseq::otu_table(ps_rel_abund)[1:5, 1:5]

phyloseq::plot_bar(ps_rel_abund, fill = "Phylum") +
  geom_bar(aes(color = Phylum, fill = Phylum), stat = "identity", position = "stack") +
  labs(x = "", y = "Relative Abundance\n") +
  facet_wrap(~ group, scales = "free") +
  theme(panel.background = element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
  scale_color_viridis(option="G", discrete = T, direction = -1) + 
  scale_fill_viridis(option="G", discrete = T, direction = -1)


plot_richness(physeq, x="group", measures=c("Chao1"), color = "group")
plot_richness(physeq_norm, x="group", measures=c("Shannon"))

tax_table(ps)[,"Phylum"] %>% unique %>% na.exclude 

sample_data(physeq)

ps_phylum <- phyloseq::tax_glom(physeq_norm, "Phylum")
phyloseq::taxa_names(ps_phylum) <- phyloseq::tax_table(ps_phylum)[, "Phylum"]

phyloseq::psmelt(phyloseq::tax_glom(ps_phylum, "Phylum")) %>%
ggplot(data = ., aes(x = group, y = Abundance)) +
  geom_boxplot(outlier.shape  = NA) +
  geom_jitter(aes(color = OTU), height = 0, width = .2) +
  labs(x = "", y = "Abundance\n") +
  facet_wrap(~ OTU, scales = "free")


shanon_div = merge(diversity(otu_table(physeq_norm), "shannon"), sam_data(physeq_norm), by = 0)

ggplot(shanon_div, aes(y = shannon, x = group, fill = group)) + geom_boxplot() + theme_test()
```


```{r}
tax_table(physeq_norm)

corncob <- bbdml(formula = . ~ , phi.formula ~ group, data = otu_table(physeq))

summary(physeq)
```


```{r}
phyloseq::taxa_names(ps_phylum) <- phyloseq::tax_table(ps_phylum)[, "Phylum"]
dds <- phyloseq_to_deseq2(physeq_filter, ~ group)
dge <- as.DGEList(dds)

dge <- calcNormFactors(dge, method = "TMM")           #store TMM norm factor
head(dge$samples$norm.factors)
mm <- model.matrix(~ group, dge$samples) 

y <- voom(dge, mm, plot = T)   

fit <- lmFit(y, mm)                                   #fit lm with limma
fit <- eBayes(fit)
head(coef(fit))

limma_res_df <- data.frame(topTable(fit, coef = "groupKerala", number = Inf))    #extract results

fdr_limma <- limma_res_df %>%
    dplyr::filter(adj.P.Val < 0.05) %>%
    rownames_to_column(var = "Species")

dim(fdr_limma)

bray_curtis = vegdist(otu_table(physeq_norm), "bray")
```


```{r}
dds <- DESeq(dds, test = "Wald", fitType = "local", sfType = "poscounts")
plotDispEsts(dds)
```


```{r}
deseq_res_df <- data.frame(res) %>%
  rownames_to_column(var = "Species") %>%
  dplyr::arrange(padj)                                 

fdr_deseq <- deseq_res_df %>%
    dplyr::filter(padj < 0.05)


phyb <- physeq_filter %>% phyloseq::subset_samples(group %in% c("A", "B")) %>% tax_glom("Phylum")
sample_data(phyb)$group

corn_da <- differentialTest(formula = ~ group, formula_null = ~ 1,
                            phi.formula_null = ~ 1, data = phyb, test = "Wald", boot = FALSE, fdr_cutoff = 0.05)

fdr_corncob <- corn_da$significant_taxa
dim(data.frame(fdr_corncob))

corncob <- bbdml(formula = OTU.1 ~ group, phi.formula = ~ 1, data = phyb)
tax_table(phyb)

da_analysis <- differentialTest(formula = ~ group, phi.formula = ~ 1, formula_null = ~ 1, phi.formula_null = ~ 1, boot = FALSE, data = phyb, fdr_cutoff = 0.05)
```




```{r}
plot_bar(physeq, fill = "Family") + theme_classic()

ds_kingdom = calculate_abundance(p = physeq, gen = "Kingdom", transpose = T)
write.csv(ds_phylum, 'kingdom_abundance.csv')
ggplot(ds_kingdom, aes(x = Sample, y = Abundance, fill = Kingdom)) + geom_bar(position="stack", stat="identity") + theme_classic() +
  scale_fill_viridis(option="G", discrete = T, direction = -1, end = 0.7) + 
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, hjust=1, vjust = 0.5))
plot_taxa_prevalence(physeq, "Kingdom") + scale_color_viridis(option="G", discrete = T, direction = -1) + 
  theme_classic() + theme(legend.position = "none")

ds_phylum = calculate_abundance(p = physeq, gen = "Phylum", transpose = T)
write.csv(ds_phylum, 'phylum_abundance.csv')
ggplot(ds_phylum, aes(x = Sample, y = Abundance, fill = Phylum)) + geom_bar(stat = 'identity') + theme_classic() +
  scale_fill_viridis(option="G", discrete = T, direction = -1) + 
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, hjust=1, vjust = 0.5))
plot_taxa_prevalence(physeq, "Phylum") + scale_color_viridis(option="G", discrete = T, direction = -1) + 
  theme_classic() + theme(legend.position = "none")

ds_class = calculate_abundance(p = physeq, gen = "Class", transpose = T)
write.csv(ds_class, 'class_abundance.csv')
ggplot(ds_class, aes(x = Sample, y = Abundance, fill = Class)) + geom_bar(stat = "identity") + theme_classic() +
  scale_fill_viridis(option="F", discrete = T, direction = -1) + 
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, hjust=1, vjust = 0.5))
plot_taxa_prevalence(physeq, "Class") + scale_color_viridis(option="F", discrete = T, direction = -1) + 
  theme_classic() + theme(legend.position = "none")

ds_order = calculate_abundance(p = physeq, gen = "Order", transpose = T)
write.csv(ds_order, 'order_abundance.csv')
ggplot(ds_order, aes(x = Sample, y = Abundance, fill = Order)) + geom_bar(stat = 'identity', aes(fill=Order)) + theme_classic() +
  scale_fill_viridis(option="C", discrete = T, direction = -1) + theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, hjust=1))
plot_taxa_prevalence(physeq, "Order") + scale_color_viridis(option="C", discrete = T, direction = -1) + labs(title = "Order") +
  theme_classic() + theme(legend.position = "none")

ds_family = calculate_abundance(p = physeq, gen = "Family", transpose = T)
write.csv(ds_family, 'family_abundance.csv')
plot_taxa_prevalence(physeq, "Family") + scale_color_viridis(option="A", discrete = T, direction = -1) + labs(title = "Family") +
  theme_classic() + theme(legend.position = "none")
```


```{r}
summarize_phyloseq(physeq_norm)
summary(sample_sums(physeq_norm))
```

```{r}
ntaxa(physeq)
nsamples(physeq)
sample_names(physeq)[1:5]  
rank_names(physeq)  
sample_variables(physeq)  
otu_table(physeq)[1:5, 1:5]  
tax_table(physeq)[1:5, 1:4]
```


```{r}
# physeq_rarefy <- rarefy_even_depth(physeq, rngseed=1, sample.size=0.9*min(sample_sums(physeq)), replace=F)

plot_anova_diversity(physeq_norm, method = c("shannon"),grouping_column =  "group", pValueCutoff=0.05) + theme_few()+   scale_color_viridis("Group", option="D", discrete = T, direction = -1, begin = 0.1, end = 0.8) + labs(x = element_blank())
```

```{r}
taxa_heatmap(calculate_abundance(p = physeq_filter, gen = "Phylum", transpose = F), metadata, "group") + 
  labs(y = element_blank()) + theme(axis.text.x = element_text(angle = 90, hjust=1, vjust = 0.5)) + scale_fill_viridis(option="G", discrete = F, direction = 1)

taxa_heatmap(calculate_abundance(p = physeq_filter, gen = "Order", transpose = F), metadata, "group") + 
  labs(y = element_blank()) + theme(axis.text.x = element_text(angle = 90, hjust=1, vjust = 0.5)) + scale_fill_viridis(option="G", discrete = F, direction = 1)
```


```{r}
plot_richness(physeq_filter, x = "group", measures = c("Observed", "Chao1", "Shannon")) + geom_boxplot(aes(fill = group), color = "black") + theme_few()+
  scale_fill_viridis("Group", option="D", discrete = T, direction = -1, begin = 0.1, end = 0.8) + labs(x = element_blank())
```

```{r}
physeq_sub = subset_taxa(physeq_filter, Phylum == "Proteobacteria")

plot_tree(physeq_sub, color = "group", shape = "Family", label.tips = "group", 
    size = "abundance", plot.margin = 0.5, ladderize = TRUE)
```



```{r}
physeq_fam <- microbiome::aggregate_rare(physeq, level = "Family", detection = 50/100, prevalence = 70/100)

physeq.fam.rel <- physeq %>%
  aggregate_rare(level = "Family", detection = 50/100, prevalence = 70/100) %>%
  microbiome::transform(transform = "compositional")

plot_composition(physeq.fam.rel,sample.sort = "group", x.label = "SampleID") + theme(legend.position = "bottom") + theme_bw() + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Relative abundance") + theme(legend.title = element_text(size = 18))

taxa_barplot(Summarize.Taxa(ASVs$data, as.data.frame(taxtable))$Family, metadata, "group")
# To make it interactive
ggplotly(taxa_barplot(Summarize.Taxa(ASVs$data, as.data.frame(taxtable))$Family, metadata, "group"))
# save the plot
b.plot <- taxa_barplot(Summarize.Taxa(ASVs$data, as.data.frame(tax_table))$Family, metadata, "group")

```


```{r}
p <- plot_taxa_heatmap(physeq,
                  subset.top = 25,
                  VariableA = c("group"),
                  transformation = "log10",
                  cluster_rows = T,
                  cluster_cols = F,
                  show_colnames = F,
                  heatcolors = colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(100),
                )
#the plot is stored here
p$plot

# table used for plot is here
p$tax_tab[1:3,1:3]
```



```{r}
h.map <- plot_heatmap(physeq.fam.rel, method="PCoA", distance="bray", taxa.label = "Family", sample.order = unique(sample_names(physeq))) + facet_grid(~group, scales = "free_x", drop = TRUE) + theme_bw() + theme(axis.text.x = element_text(face = "bold", angle = 45, hjust = 1)) + theme(legend.key = element_blank(),strip.background = element_rect(colour="black", fill="white"))

# Make bacterial names italics
h.map <- h.map + theme(axis.text.y = element_text(colour = 'black', size = 10, face = 'italic'))

# Change the color palette
h.map <- h.map + scale_fill_distiller("Abundance", palette = "RdYlBu")

# clean the x-axis
h.map <- h.map + rremove("x.text")

print(h.map)
```


```{r}
physeq.genus <- aggregate_taxa(physeq, "Genus")
top_four <- top_taxa(physeq.genus, 4)
top_four

top_genera <- plot_listed_taxa(physeq.genus, top_four, group= "group")
top_genera

top_genera + stat_compare_means(
                   comparisons = comps,
                   label = "p.format",
                   tip.length = 0.05,
                   method = "wilcox.test")
```


```{r}
physeq.gen <- aggregate_taxa(physeq,"Genus")

dom.tax <- dominant_taxa(physeq,level = "Genus", group="group")
head(dom.tax$dominant_overview)
```


```{r}
grp_abund <- get_group_abundances(physeq_filter, level = "Phylum", group="group",  transform = "compositional")
grp_abund %>% ggplot(aes(x= reorder(OTUID, mean_abundance), y= mean_abundance, fill=group)) + 
  geom_bar(stat = "identity", position=position_dodge()) + ylab("Mean Relative Abundance") +
  xlab("Species") + coord_flip() + scale_fill_viridis("Group", option="G", discrete = T, direction = -1) + 
  theme_classic() + theme()
  
```

```{r}
taxa_summary(physeq, "Phylum")
```


```{r}
ggrare(physeq, step = 50, color="group", label = "Sample", se = TRUE) ############# WOLNE ##############
```


```{r}
physeq_rarefy <- rarefy_even_depth(physeq_filter, rngseed=1, sample.size=0.9*min(sample_sums(physeq_filter)), replace=F)
plot_richness(physeq_rarefy, measures="Shannon", color = "group") + geom_boxplot() + theme_bw()
```


```{r}
physeq_df <- microbiomeutilities::phy_to_ldf(physeq_fam, transform.counts = "compositional")

# An additonal column Sam_rep with sample names is created for reference purpose
colnames(physeq_df)

# Box plot at Family level

ggstripchart(physeq_df, "group", "Abundance", 
             facet.by = "Family", color = "group",
             palette = "jco") + rremove("x.text")
```

```{r}
physeq.ord <- ordinate(physeq_rarefy, "PCoA", "bray")
b.div.bray <- plot_ordination(physeq_rarefy, physeq.ord, type= "samples", color= "group") + geom_point(size=3)
b.div.bray <- b.div.bray + stat_ellipse() + ggtitle("Bray Curtis")  + theme_classic() + scale_color_brewer("Location", palette = "Set2")
print(b.div.bray)
```


```{r}
physeq_rel <- microbiome::transform(physeq, "compositional")
physeq.ord.wuni <- ordinate(physeq_rel, "PCoA", "unifrac", weighted=T)
b.div.wuni <- plot_ordination(physeq_rel, physeq.ord.wuni, type= "samples", color= "group") + geom_point(size=3)
b.div.wuni <- b.div.wuni + stat_ellipse() + ggtitle("Weighted Unifrac")  + theme_classic() + scale_color_brewer("Location", palette = "Set2")
print(b.div.wuni)
```


```{r}
otu <- abundances(physeq_rel)
meta <- meta(physeq_rel)

#Statistics - Bdiv
permanova <- adonis(t(otu) ~ group, data = meta, permutations=99, method = "bray")

#P-value
print(as.data.frame(permanova$aov.tab)["group", "Pr(>F)"])
```


```{r}
physeq.gut <- subset_samples(physeq, group == "A")

# convert to relative abundance  
physeq.gut.rel <- microbiome::transform(physeq.gut, "compositional")

physeq.gut.rel2 <- prune_taxa(taxa_sums(physeq.gut.rel) > 0, physeq.gut.rel)
```


```{r}
core.taxa.standard <- core_members(physeq.gut.rel2, detection = 0.001, prevalence = 50/100)
print(core.taxa.standard)
```


```{r}
# Extract the taxonomy table
taxonomy_core <- as.data.frame(tax_table(physeq.gut.rel2))

# Subset this taxonomy table to include only core OTUs
core_taxa_id <- subset(taxonomy_core, rownames(taxonomy_core) %in% core.taxa.standard)

core_taxa_id
```


```{r}
core.abundance <- sample_sums(core(physeq.gut.rel2, detection = 0.001, prevalence = 50/100))

as.data.frame(core.abundance)
```

```{r}
# Core with compositionals:
prevalences <- seq(.05, 1, .05)
detections <- 10^seq(log10(1e-3), log10(.2), length = 10)

# Also define color palette
gray <- gray(seq(0,1,length=5))
p.core <- plot_core(physeq.gut.rel2, 
                    plot.type = "heatmap", 
                    colours = rev(brewer.pal(5, "Spectral")),
                    prevalences = prevalences, 
                    detections = detections, 
                    min.prevalence = .5) +
  xlab("Detection Threshold (Relative Abundance (%))")
print(p.core)
```


```{r}
physeq.gut.rel2.f <- microbiomeutilities::format_to_besthit(physeq.gut.rel2)

p.core <- plot_core(physeq.gut.rel2.f, 
                    plot.type = "heatmap", 
                    colours = rev(brewer.pal(5, "Spectral")),
                    prevalences = prevalences, 
                    detections = detections, 
                    min.prevalence = .5) + 
  xlab("Detection Threshold (Relative Abundance (%))")

p.core + theme(axis.text.y = element_text(face="italic"))
```


```{r}
library(ggrepel)

physeq_comp <- microbiome::transform(physeq, "compositional")
# select gut
physeq_comp_gut <- subset_samples(physeq_comp, group=="A")

physeq_comp_gut <- core(physeq_comp_gut,detection = 0.0001, prevalence = 0.50) # reduce size for example

physeq_comp_gut <- format_to_besthit(physeq_comp_gut)

set.seed(163897)
prevalance <- plot_abund_prev(physeq_comp_gut, 
                       label.core = TRUE,
                       color = "Phylum", # NA or "blue"
                       mean.abund.thres = 0.01,
                       mean.prev.thres = 0.99,
                       dot.opacity = 0.7,
                       label.size = 3,
                       label.opacity = 1.0,
                       nudge.label=-0.15,
                       bs.iter=999, # increase for actual analysis e.g. 999
                       size = 20, # increase to match your nsamples(asv_ps)
                       replace = TRUE,
                       label.color="#5f0f40") 
prevelance <- prevalance + 
  geom_vline(xintercept = 0.95, lty="dashed", alpha=0.7) + 
  geom_hline(yintercept = 0.01,lty="dashed", alpha=0.7) +
  scale_color_brewer(palette = "Dark2")

prevelance
```


```{r}
physeq_top_50 <- subset_taxa(physeq, Phylum=="Bacteroidetes")
physeq_top_50 <- prune_taxa(names(sort(taxa_sums(physeq_top_50),TRUE)[1:50]), physeq_top_50)

# Default plot tree
plot_tree(physeq_top_50)

# Add genus labels to the tree and bootstrap values
plot_tree(physeq_top_50, label.tips="Genus", ladderize="left")

# Remove bootstrap values
plot_tree(physeq_top_50, nodelabf=nodeplotblank, label.tips="Genus", ladderize="left")

# Color the nodes by category
plot_tree(physeq_top_50, nodelabf=nodeplotblank, label.tips="Genus", ladderize="left", color="group")

# Add size by abundance
plot_tree(physeq_top_50, nodelabf=nodeplotblank, label.tips="Genus", ladderize="left", color="group", size="abundance")

# Convert to radial tree
plot_tree(physeq_top_50, nodelabf=nodeplotblank, label.tips="Genus", ladderize="left", color="group") + coord_polar(theta="y")
```


```{r}
phy.hclust <- hclust(UniFrac(physeq_rarefy, weighted = TRUE), method="average")

ggdendrogram(phy.hclust, rotate = TRUE, theme_dendro = TRUE)
```


```{r}
plot_net(physeq_rel, maxdist = 0.8, color = "group")
#change distance to Jaccard
plot_net(physeq_rel, maxdist = 0.8, color = "group", distance="jaccard")
```


```{r}
ig <- make_network(physeq_rel, max.dist=0.8)
plot_network(ig, physeq_rel)

# Add color label 
plot_network(ig, physeq_rel, color="group", line_weight=0.4, label=NULL)

#replace the Jaccard (default) distance method with Bray-Curtis
ig <- make_network(physeq_rel, dist.fun="bray", max.dist=0.8)
plot_network(ig, physeq_rel, color="group", line_weight=0.4, label=NULL)
```

```{r}
#Convert phyloseq object ot DeSeq
bsdds <- phyloseq_to_deseq2(physeq_rarefy, ~ group)
gm_mean <- function(x, na.rm=TRUE){
  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
}
geoMeans <- apply(counts(bsdds), 1, gm_mean)
bsdds <- estimateSizeFactors(bsdds, geoMeans = geoMeans)
# DeSeq function tests for differential abundance 
bsdds <- DESeq(bsdds, test="Wald", fitType="parametric")

# Results function call creates a table of the results of the tests
res <- results(bsdds, cooksCutoff = FALSE)
alpha <- 0.01
sigtab <- res[which(res$padj < alpha), ]
sigtab <- cbind(as(sigtab, "data.frame"), as(tax_table(physeq_rarefy)[rownames(sigtab), ], "matrix"))
head(sigtab)

# Cleaning up the table a little for legibility
posigtab <- sigtab[sigtab[, "log2FoldChange"] > 0, ]
posigtab <- posigtab[, c("baseMean", "log2FoldChange", "lfcSE", "padj", "Phylum", "Class", "Family", "Genus")]

# Bar plot showing the log2-fold-change, showing Genus and Phylum. Uses some ggplot2 commands
sigtabgen <- subset(sigtab, !is.na(Genus))
# Phylum order
x <- tapply(sigtabgen$log2FoldChange, sigtabgen$Phylum, function(x) max(x))
x <- sort(x, TRUE)
sigtabgen$Phylum = factor(as.character(sigtabgen$Phylum), levels=names(x))
# Genus order
x <- tapply(sigtabgen$log2FoldChange, sigtabgen$Genus, function(x) max(x))
x <- sort(x, TRUE)
sigtabgen$Genus = factor(as.character(sigtabgen$Genus), levels=names(x))
ggplot(sigtabgen, aes(y=Genus, x=log2FoldChange, color=Phylum)) + 
  geom_vline(xintercept = 0.0, color = "gray", size = 0.5) +
  geom_point(size=6) + 
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))
```




